global:
  scrape_interval: 5s # Set scrape interval to 5 seconds for quicker load testing feedback

scrape_configs:
  - job_name: 'restaurant-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['host.docker.internal:8080'] # Assuming Gin default port 8000, modify if app uses different port
